#!/usr/bin/env bash
# Installs an extracted version of a notion
# tarball generated by build.sh
set -euo pipefail

# INSTALL_DIR is the directory where Notion will be installed.
INSTALL_DIR="$HOME/.local/share/notion-rewrapped"

# create_shortcut 
cat <<EOS > "$HOME/.local/share/applications/Notion.desktop"
[Desktop Entry]
Name=Notion
Name[en_US]=Notion
Comment=Unofficial Notion application for Linux
Exec=$HOME/.local/bin/notion-rewrapped --force-device-scale-factor=1.25
Terminal=false
Categories=Office;TextEditor;Utility
Type=Application
Icon=${INSTALL_DIR}/Notion_app_logo.png
StartupWMClass=notion
EOS
chmod +x "$HOME/.local/share/applications/Notion.desktop"


# install
mkdir -p "$INSTALL_DIR"
cp -rvp release/* "$INSTALL_DIR"
cp $INSTALL_DIR/notion-rewrapped $HOME/.local/bin/notion-rewrapped